# Generated by Django 5.1.2 on 2024-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_pic', models.FileField(upload_to='teams/')),
                ('tweeter_url', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
            ],
        ),
    ]
